'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { modelDefinition, modelName, type ResearchModel } from '../lib/model-catalog';
import { buildResearchSignal } from '../lib/research-signal';
import type { MarketQuote, OhlcBar, PairSymbol, Timeframe } from '../lib/market-data';

type Language = 'zh' | 'ja' | 'en';
type ObservationOutcome = 'pending' | 'consistent' | 'inconsistent' | 'skipped';
type ObservationSource = 'automatic' | 'manual';
interface ForwardCandidate { model: ResearchModel; time: string; score: number; }
interface ForwardProtocol { id: string; model: ResearchModel; startedAt: string; daysTarget: number; observationsTarget: number; maxInvalidRatePct: number; autoCapture: boolean; paused: boolean; baselineCandleTime: number; reviewHorizon: number; }
interface ForwardObservation { id: string; model: ResearchModel; symbol: PairSymbol; timeframe: Timeframe; candleTime: number; recordedAt: string; direction: 'long' | 'short' | 'wait'; score: number; close: number; outcome: ObservationOutcome; note: string; source: ObservationSource; generatedNote?: boolean; reviewHorizon?: number; }

function loadLocal<T>(key: string, fallback: T) { if (typeof window === 'undefined') return fallback; try { return JSON.parse(window.localStorage.getItem(key) ?? '') as T; } catch { return fallback; } }
function normaliseProtocol(raw: ForwardProtocol | null): ForwardProtocol | null { if (!raw) return null; return { id: raw.id ?? `forward-${raw.startedAt}`, model: raw.model, startedAt: raw.startedAt, daysTarget: raw.daysTarget ?? 21, observationsTarget: raw.observationsTarget ?? 40, maxInvalidRatePct: raw.maxInvalidRatePct ?? 30, autoCapture: raw.autoCapture ?? true, paused: raw.paused ?? false, baselineCandleTime: raw.baselineCandleTime ?? 0, reviewHorizon: raw.reviewHorizon ?? 3 }; }
function daysBetween(iso: string) { return Math.max(0, Math.floor((Date.now() - new Date(iso).getTime()) / 86_400_000)); }

export default function ForwardValidation({ language, quote, bars, symbol, timeframe, historyReady, activeModel, onModelChange, displayTimeZone = 'Asia/Tokyo' }: { language: Language; quote: MarketQuote; bars: OhlcBar[]; symbol: PairSymbol; timeframe: Timeframe; historyReady: boolean; activeModel: ResearchModel; onModelChange: (model: ResearchModel) => void; displayTimeZone?: string }) {
  const [candidates] = useState<ForwardCandidate[]>(() => loadLocal('enkei-forward-paper-queue', []));
  const [protocol, setProtocol] = useState<ForwardProtocol | null>(() => normaliseProtocol(loadLocal<ForwardProtocol | null>('enkei-forward-validation-protocol', null)));
  const [observations, setObservations] = useState<ForwardObservation[]>(() => loadLocal('enkei-forward-validation-observations', []));
  const [daysTarget, setDaysTarget] = useState(21);
  const [observationsTarget, setObservationsTarget] = useState(40);
  const [maxInvalidRatePct, setMaxInvalidRatePct] = useState(30);
  const [reviewHorizon, setReviewHorizon] = useState(3);
  const [note, setNote] = useState('');
  const t = useCallback((zh: string, ja: string, en = zh) => language === 'zh' ? zh : language === 'ja' ? ja : en, [language]);
  const bilingual = (zh: string, ja: string, english: string) => t(zh, ja, english);
  const completedBar = bars.at(-2);
  const queued = candidates.find((item) => item.model === (protocol?.model ?? activeModel)) ?? candidates.find((item) => item.model === activeModel) ?? candidates[0];
  const candidate = queued ?? { model: activeModel, time: new Date().toISOString(), score: 0 };
  const model = protocol?.model ?? candidate.model;
  const signal = useMemo(() => buildResearchSignal(bars, symbol, timeframe, model), [bars, model, symbol, timeframe]);
  const protocolObservations = observations.filter((item) => item.model === model && (!protocol || item.recordedAt >= protocol.startedAt));
  const reviewed = protocolObservations.filter((item) => item.outcome === 'consistent' || item.outcome === 'inconsistent');
  const inconsistent = reviewed.filter((item) => item.outcome === 'inconsistent').length;
  const invalidRate = reviewed.length ? inconsistent / reviewed.length * 100 : 0;
  const elapsedDays = protocol ? daysBetween(protocol.startedAt) : 0;
  const durationMet = protocol ? elapsedDays >= protocol.daysTarget : false;
  const observationMet = protocol ? reviewed.length >= protocol.observationsTarget : false;
  const qualityMet = protocol ? invalidRate <= protocol.maxInvalidRatePct : false;
  const forwardReady = Boolean(protocol && durationMet && observationMet && qualityMet);

  useEffect(() => { window.localStorage.setItem('enkei-forward-validation-protocol', JSON.stringify(protocol)); }, [protocol]);
  useEffect(() => { window.localStorage.setItem('enkei-forward-validation-observations', JSON.stringify(observations)); }, [observations]);

  const addObservation = useCallback((source: ObservationSource, manualNote = '') => {
    if (!protocol || !historyReady || !completedBar) return;
    if (source === 'automatic' && (protocol.paused || !protocol.autoCapture || completedBar.time <= protocol.baselineCandleTime)) return;
    setObservations((current) => {
      const exists = current.some((item) => item.model === protocol.model && item.symbol === symbol && item.timeframe === timeframe && item.candleTime === completedBar.time && item.recordedAt >= protocol.startedAt);
      if (exists) return current;
      const prefix = source === 'automatic' ? t('自动捕捉：等待后续', '自動記録：後続確認待ち', 'Auto-captured: awaiting outcome') : t('手动记录：等待后续', '手動記録：後続確認待ち', 'Manually recorded: awaiting outcome');
      const observation: ForwardObservation = { id: `forward-${Date.now()}`, model: protocol.model, symbol, timeframe, candleTime: completedBar.time, recordedAt: new Date().toISOString(), direction: signal.direction, score: signal.score, close: completedBar.close, outcome: 'pending', note: manualNote || `${prefix} ${protocol.reviewHorizon} ${t('根完成K线', '本の確定足', 'completed candles')}`, source, generatedNote: !manualNote, reviewHorizon: protocol.reviewHorizon };
      return [observation, ...current].slice(0, 480);
    });
  }, [completedBar, historyReady, protocol, signal.direction, signal.score, symbol, t, timeframe]);

  useEffect(() => { if (!protocol?.autoCapture || protocol.paused || !completedBar || !historyReady) return; const timer = window.setTimeout(() => addObservation('automatic'), 0); return () => window.clearTimeout(timer); }, [addObservation, completedBar, historyReady, protocol?.autoCapture, protocol?.paused, protocol?.baselineCandleTime, protocol?.startedAt]);

  const startProtocol = () => { if (!historyReady) return; onModelChange(candidate.model); setProtocol({ id: `forward-${Date.now()}`, model: candidate.model, startedAt: new Date().toISOString(), daysTarget, observationsTarget, maxInvalidRatePct, autoCapture: true, paused: false, baselineCandleTime: completedBar?.time ?? 0, reviewHorizon }); };
  const setOutcome = (id: string, outcome: ObservationOutcome) => setObservations((current) => current.map((item) => item.id === id ? { ...item, outcome } : item));
  const exportAudit = () => { const payload = { generatedAt: new Date().toISOString(), protocol, observations: protocolObservations, metrics: { elapsedDays, reviewed: reviewed.length, inconsistent, invalidRatePct: Number(invalidRate.toFixed(2)), status: forwardReady ? 'human-review-only' : 'observation-in-progress' }, boundaries: { noOrders: true, noBrokerAccess: true, noAutoPromotion: true, demoExecutionGateMustRemainLocked: true } }; const url = URL.createObjectURL(new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'enkei-forward-validation-report.json'; anchor.click(); URL.revokeObjectURL(url); };
  const labelDirection = (value: ForwardObservation['direction']) => value === 'long' ? bilingual('偏多观察', '買い観測', 'long') : value === 'short' ? bilingual('偏空观察', '売り観測', 'short') : bilingual('观望', '待機', 'wait');
  const labelOutcome = (value: ObservationOutcome) => value === 'consistent' ? bilingual('逻辑一致', 'ロジック一致', 'consistent') : value === 'inconsistent' ? bilingual('逻辑不一致', 'ロジック不一致', 'inconsistent') : value === 'skipped' ? bilingual('不计入样本', '標本から除外', 'skipped') : bilingual('等待人工复核', '人による確認待ち', 'pending');
  const observationNote = (item: ForwardObservation) => {
    const legacy = /(?:自动捕捉|自動記録|Auto-captured|手动记录|手動記録|Manually recorded).*(\d+)\s*(?:根完成K线|本の確定足|completed candles)/i.exec(item.note);
    if (!item.generatedNote && !legacy) return item.note || t('无备注', 'メモなし', 'No notes');
    const horizon = item.reviewHorizon ?? Number(legacy?.[1] ?? protocol?.reviewHorizon ?? 3);
    return `${t('等待后续', '後続確認待ち', 'awaiting outcome')} ${horizon} ${t('根完成K线', '本の確定足', 'completed candles')}`;
  };
  const formatTime = (time: number) => new Intl.DateTimeFormat(language === 'zh' ? 'zh-CN' : language === 'ja' ? 'ja-JP' : 'en-US', { timeZone: displayTimeZone, month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', hourCycle: 'h23' }).format(new Date(time * 1000));
  const scorecard = useMemo(() => { const models = Array.from(new Set([candidate.model, activeModel, ...candidates.map((item) => item.model)])); return models.map((item) => { const rows = observations.filter((observation) => observation.model === item); const checked = rows.filter((observation) => observation.outcome === 'consistent' || observation.outcome === 'inconsistent'); const pass = checked.filter((observation) => observation.outcome === 'consistent').length; return { model: item, recorded: rows.length, checked: checked.length, consistency: checked.length ? pass / checked.length * 100 : null }; }).sort((a, b) => (b.consistency ?? -1) - (a.consistency ?? -1)); }, [activeModel, candidate.model, candidates, observations]);

  return <section className="phase-panel forward-validation">
    <div className="phase-heading"><div><p className="eyebrow">{bilingual('第十一阶段：前向验证', '第11段階：フォワード検証', 'Phase 11 · Forward validation')}</p><h3>{t('前向验证工作台', 'フォワード検証ワークベンチ', 'Forward-validation workbench')} <span>{bilingual('未来完成K线 · 人工复核 · 不产生订单', '将来の確定足・人による確認・注文なし', 'completed bars · human review · no orders')}</span></h3></div><span className="model-local-chip">{bilingual('浏览器本机记录', 'ブラウザ端末内記録', 'local-only')}</span></div>
    <div className="forward-safety"><span>◈</span><p><b>{t('前向验证检验策略在之后的市场环境中是否仍保持逻辑一致；它不能证明“持续盈利”，也不会自动挑选或升级策略。', 'フォワード検証は、その後の市場環境でも戦略ロジックが一貫しているかを確認します。「継続的に利益が出る」ことの証明でも、自動選抜・自動昇格でもありません。', 'Forward validation checks whether the strategy stays logically consistent in later markets; it cannot prove “sustained profit” and never auto-selects or promotes strategies.')}</b><small>{t('本页只记录已经完成的K线和你的复核结论。不发送订单、不读取账户、不连接乐天交易功能；Demo 执行确认服务应继续保持急停。', 'このページは確定足とあなたの確認結果だけを記録します。注文送信・口座読取・楽天取引機能への接続はありません。Demo実行確認サービスは緊急停止のままにしてください。', 'This page records only completed candles and your review conclusions. It sends no orders, reads no account and connects to no Rakuten trading features; the Demo confirmation service should stay emergency-stopped.')}</small></p></div>
    <div className="forward-protocol"><article><span>{bilingual('研究模型', '研究モデル', 'research model')}</span><b>{modelName(modelDefinition(candidate.model), language)}</b><small>{queued ? `${bilingual('筛选研究分', '選抜研究スコア', 'selection score')} ${candidate.score.toFixed(1)}` : bilingual('当前活动模型', '現在の有効モデル', 'active model')} · {bilingual('复核等待K线', '確認までの確定足', 'review horizon')} {protocol?.reviewHorizon ?? reviewHorizon}</small><input disabled={Boolean(protocol)} aria-label={bilingual('复核等待K线数', '確認までの確定足数', 'review horizon')} type="range" min="1" max="12" value={protocol?.reviewHorizon ?? reviewHorizon} onChange={(event) => setReviewHorizon(Number(event.target.value))} /></article><label><span>{bilingual('最短观察周期', '最短観察期間', 'minimum calendar days')}</span><b>{protocol?.daysTarget ?? daysTarget} {t('天', '日', 'days')}</b><input disabled={Boolean(protocol)} type="range" min="14" max="120" step="1" value={protocol?.daysTarget ?? daysTarget} onChange={(event) => setDaysTarget(Number(event.target.value))} /></label><label><span>{bilingual('最少人工复核数', '最小の人による確認数', 'minimum reviewed observations')}</span><b>{protocol?.observationsTarget ?? observationsTarget}</b><input disabled={Boolean(protocol)} type="range" min="10" max="120" step="5" value={protocol?.observationsTarget ?? observationsTarget} onChange={(event) => setObservationsTarget(Number(event.target.value))} /></label><label><span>{bilingual('最大逻辑不一致率', '許容ロジック不一致率', 'maximum inconsistency rate')}</span><b>{protocol?.maxInvalidRatePct ?? maxInvalidRatePct}%</b><input disabled={Boolean(protocol)} type="range" min="10" max="60" step="5" value={protocol?.maxInvalidRatePct ?? maxInvalidRatePct} onChange={(event) => setMaxInvalidRatePct(Number(event.target.value))} /></label><div className="forward-protocol-actions"><button onClick={startProtocol} disabled={Boolean(protocol) || !historyReady}>{protocol ? bilingual('验证进行中', '検証進行中', 'running') : historyReady ? bilingual('开始前向验证', 'フォワード検証を開始', 'start') : bilingual('等待校准历史', '補正済み履歴を待機', 'history required')}</button><button onClick={exportAudit} disabled={!protocol}>{bilingual('导出阶段报告', '段階レポートを書き出す', 'export report')}</button></div></div>
    {protocol && <><div className="forward-milestones"><article className={durationMet ? 'done' : ''}><span>①</span><b>{elapsedDays}/{protocol.daysTarget} {t('天', '日', 'days')}</b><small>{bilingual('日历观察', 'カレンダー観察', 'calendar')}</small></article><article className={observationMet ? 'done' : ''}><span>②</span><b>{reviewed.length}/{protocol.observationsTarget}</b><small>{bilingual('人工复核', '人による確認', 'human review')}</small></article><article className={qualityMet ? 'done' : ''}><span>③</span><b>{invalidRate.toFixed(1)}% / {protocol.maxInvalidRatePct}%</b><small>{bilingual('逻辑不一致率', 'ロジック不一致率', 'inconsistency')}</small></article><article className={forwardReady ? 'done' : ''}><span>④</span><b>{forwardReady ? bilingual('可人工审查', '人による審査可能', 'review eligible') : bilingual('继续采样', '標本収集中', 'collecting')}</b><small>{bilingual('不会自动升级', '自動昇格なし', 'no auto promotion')}</small></article></div>
      <div className="forward-current"><div><p className="eyebrow">{bilingual('当前完成K线', '現在の確定足', 'current completed bar')}</p><b>{symbol} · {timeframe} · {labelDirection(signal.direction)}</b><span>{completedBar ? `${formatTime(completedBar.time)} · ${completedBar.close.toFixed(symbol.endsWith('/JPY') ? 3 : 5)} · ${bilingual('信号强度', 'シグナル強度', 'score')} ${signal.score}` : t('等待完成K线', '確定足を待機', 'Waiting for completed candles')}</span><small>{historyReady ? bilingual('来自已校准 MT4 历史；只记录完成K线', '補正済みMT4履歴から取得；確定足のみ記録', 'calibrated MT4 history') : bilingual('历史尚未校准，禁止记录', '履歴未補正のため記録禁止', 'history not qualified')}</small></div><label><span>{bilingual('人工备注（可选）', '手動メモ（任意）', 'manual note')}</span><input value={note} maxLength={140} onChange={(event) => setNote(event.target.value)} placeholder={t('例如：重大事件前，仅记录不评分', '例：重要イベント前のため、記録のみで評価しない', 'e.g. around major events, record without scoring')} /></label><button onClick={() => { addObservation('manual', note.trim()); setNote(''); }} disabled={!historyReady || !completedBar || protocolObservations.some((item) => item.symbol === symbol && item.timeframe === timeframe && item.candleTime === completedBar.time)}>{bilingual('手动记录此K线', 'この足を手動記録', 'record bar')}</button></div>
      <div className="forward-control"><label><input type="checkbox" checked={protocol.autoCapture} onChange={(event) => setProtocol((current) => current ? { ...current, autoCapture: event.target.checked } : current)} />{bilingual('自动捕捉新完成K线', '新しい確定足を自動記録', 'auto capture')}</label><label><input type="checkbox" checked={!protocol.paused} onChange={(event) => setProtocol((current) => current ? { ...current, paused: !event.target.checked } : current)} />{bilingual('继续采样', '標本収集を継続', 'collection enabled')}</label><label>{bilingual('复核等待K线数', '確認までの確定足数', 'review horizon')} <b>{protocol.reviewHorizon}</b><input type="range" min="1" max="12" value={protocol.reviewHorizon} onChange={(event) => setProtocol((current) => current ? { ...current, reviewHorizon: Number(event.target.value) } : current)} /></label><small>{protocol.paused ? bilingual('采样已暂停；已有记录不会被删除', '標本収集は停止中；既存記録は削除されません', 'paused') : bilingual('自动捕捉只从启动后出现的新完成K线开始', '自動記録は開始後に生じた新しい確定足からのみ', 'future bars only')}</small></div>
      <div className="forward-list"><div className="section-title"><b>{bilingual('前向观察清单', 'フォワード観察一覧', 'forward observation log')}</b><span>{quote.symbol} {quote.bid.toFixed(quote.symbol.endsWith('/JPY') ? 3 : 5)} · {bilingual('只读报价', '読取専用レート', 'read-only quote')}</span></div>{protocolObservations.map((item) => <div className="forward-row" key={item.id}><time>{formatTime(item.candleTime)}</time><div><b>{item.symbol} · {item.timeframe} · {labelDirection(item.direction)} · {bilingual('强度', '強度', 'score')} {item.score}</b><small>{item.source === 'automatic' ? bilingual('自动捕捉', '自動記録', 'auto captured') : bilingual('手动记录', '手動記録', 'manually recorded')} · {observationNote(item)}</small></div><div className="forward-review"><button className={item.outcome === 'consistent' ? 'active positive' : ''} onClick={() => setOutcome(item.id, 'consistent')}>{bilingual('一致', '一致', 'consistent')}</button><button className={item.outcome === 'inconsistent' ? 'active negative' : ''} onClick={() => setOutcome(item.id, 'inconsistent')}>{bilingual('不一致', '不一致', 'inconsistent')}</button><button className={item.outcome === 'skipped' ? 'active' : ''} onClick={() => setOutcome(item.id, 'skipped')}>{bilingual('不计入', '除外', 'skip')}</button><small>{labelOutcome(item.outcome)}</small></div></div>)}{protocolObservations.length === 0 && <p className="empty-state">{bilingual('等待新的完成K线；启动前已有的历史K线不会被混入前向样本', '新しい確定足を待機；開始前の履歴足はフォワード標本に混入しません', 'future samples only')}</p>}</div>
      <div className="forward-scorecard"><div className="section-title"><b>{bilingual('策略观察对比', '戦略観察比較', 'strategy observation comparison')}</b><span>{bilingual('只做研究排序，不自动启用任何模型', '研究上の並び替えのみ。モデルは自動有効化しません', 'research only')}</span></div>{scorecard.map((item) => <article key={item.model}><b>{modelName(modelDefinition(item.model), language)}</b><span>{bilingual('记录', '記録', 'recorded')} {item.recorded} · {bilingual('已复核', '確認済み', 'reviewed')} {item.checked}</span><strong>{item.consistency === null ? bilingual('样本不足', '標本不足', 'insufficient sample') : `${bilingual('一致率', '一致率', 'consistency')} ${item.consistency.toFixed(1)}%`}</strong></article>)}</div></>}
    <div className="forward-rules"><article><p className="eyebrow">{bilingual('通过条件', '通過条件', 'pass condition')}</p><b>{t('三道门全部完成', '3つのゲートをすべて完了', 'All three gates completed')}</b><span>{t('观察周期、人工复核数和逻辑不一致率都满足目标，才显示“可人工审查”。这不是实盘许可。', '観察期間・人による確認数・ロジック不一致率がすべて目標を満たした時だけ「人による審査可能」と表示されます。実取引の許可ではありません。', '“Ready for human review” appears only when observation period, human review count and logic-mismatch rate all meet the targets. This is not a live-trading licence.')}</span></article><article><p className="eyebrow">{bilingual('复核方法', '確認方法', 'review method')}</p><b>{t('只评估事先记录的逻辑', '事前に記録したロジックだけを評価', 'Only pre-recorded logic is evaluated')}</b><span>{t('在设定的等待K线数后，再与市场结构、成本和事件环境对照。可判定“不计入”，但不会删除原始记录。', '設定した確定足数の後、市場構造・コスト・イベント環境と照合します。「除外」は可能ですが、元記録は削除しません。', 'After the configured waiting candles, results are checked against market structure, costs and events. Entries can be marked “excluded”, but raw records are never deleted.')}</span></article><article><p className="eyebrow">{bilingual('安全边界', '安全境界', 'safety boundary')}</p><b>{t('不会产生订单', '注文を生成しない', 'Produces no orders')}</b><span>{t('即使未来达到前向观察门槛，下一步仍只是人工审查和延长模拟；任何真实执行都需要独立的明确授权。', '将来フォワード観察の条件を満たしても、次は人による審査と長期のペーパーです。実行には独立した明確な承認が必要です。', 'Even if the forward-observation threshold is met in future, the next step is still human review and extended simulation; any real execution requires separate explicit authorisation.')}</span></article></div>
  </section>;
}
