import { DEFAULT_BACKTEST_CONFIG, runBacktest } from './backtest';
import { RESEARCH_MODELS, type ResearchModel } from './model-catalog';
import { QUOTES, type OhlcBar, type PairSymbol, type RiskConfig, type Timeframe } from './market-data';

export type AutonomousTimeframe = 'M1' | 'M5' | 'M15' | 'H1';
export interface AdaptiveHistory { symbol: PairSymbol; bars: OhlcBar[]; }
export interface AdaptiveObservation { model: ResearchModel; outcome: 'pending' | 'consistent' | 'inconsistent' | 'skipped'; }
export interface AdaptiveModelScore { model: ResearchModel; score: number; averageReturnPct: number; worstDrawdownPct: number; passMarkets: number; totalMarkets: number; forwardReviewed: number; invalidRatePct: number; eligible: boolean; }
export interface AdaptiveAudit { id: string; time: string; type: 'evaluation' | 'switch' | 'queued' | 'suspended' | 'waiting'; text: string; }
export interface AutonomousDecision { timeframe: AutonomousTimeframe; selectedModel: ResearchModel; leaderModel: ResearchModel | null; leaderStreak: number; lastEvaluationAt: string | null; dataMarkets: number; scores: AdaptiveModelScore[]; }
export interface AdaptiveState { enabled: boolean; selectedModel: ResearchModel; leaderModel: ResearchModel | null; leaderStreak: number; lastEvaluationAt: string | null; dataMarkets: number; scores: AdaptiveModelScore[]; suspendedModels: ResearchModel[]; timeframeDecisions: Partial<Record<AutonomousTimeframe, AutonomousDecision>>; audits: AdaptiveAudit[]; }
const STORAGE_KEY = 'enkei-adaptive-research-state';
export const INITIAL_ADAPTIVE_STATE: AdaptiveState = { enabled: true, selectedModel: 'trend-breakout', leaderModel: null, leaderStreak: 0, lastEvaluationAt: null, dataMarkets: 0, scores: [], suspendedModels: [], timeframeDecisions: {}, audits: [] };
function profileSettings() { const ratio = .45; return { fastEma: Math.round(22 - ratio * 16), slowEma: Math.round(58 - ratio * 40), breakoutLookback: Math.round(32 - ratio * 24), stopAtr: Number((2.4 - ratio * 1.4).toFixed(1)), rewardRisk: Number((1.5 + ratio * 1.4).toFixed(1)), maxHoldingBars: Math.round(72 - ratio * 56) }; }
function forwardQuality(observations: AdaptiveObservation[], model: ResearchModel) { const reviewed = observations.filter((item) => item.model === model && (item.outcome === 'consistent' || item.outcome === 'inconsistent')); const inconsistent = reviewed.filter((item) => item.outcome === 'inconsistent').length; return { reviewed: reviewed.length, invalidRatePct: reviewed.length ? inconsistent / reviewed.length * 100 : 0 }; }
export function evaluateAdaptiveModels(histories: AdaptiveHistory[], timeframe: Timeframe, risk: RiskConfig, observations: AdaptiveObservation[], suspended: ResearchModel[], confirmedWeights: Partial<Record<ResearchModel, number>> = {}): AdaptiveModelScore[] { const settings = profileSettings(); return RESEARCH_MODELS.map((definition) => { const rows = histories.map((history) => { const quote = QUOTES.find((item) => item.symbol === history.symbol) ?? QUOTES[0]; const result = runBacktest(history.bars, { ...DEFAULT_BACKTEST_CONFIG, ...settings, symbol: history.symbol, timeframe, riskPerTradePct: risk.riskPerTradePct, spreadPips: quote.spreadPips, entryModel: definition.id, startIndex: Math.floor(history.bars.length * .7) }); return { pass: result.netReturnPct > 0 && result.profitFactor > 1 && result.totalTrades >= 10 && result.maxDrawdownPct <= 8, returnPct: result.netReturnPct, drawdownPct: result.maxDrawdownPct, trades: result.totalTrades }; }); const averageReturnPct = rows.length ? rows.reduce((sum, item) => sum + item.returnPct, 0) / rows.length : 0; const worstDrawdownPct = rows.length ? Math.max(...rows.map((item) => item.drawdownPct)) : 0; const passMarkets = rows.filter((item) => item.pass).length; const { reviewed, invalidRatePct } = forwardQuality(observations, definition.id); const eligible = passMarkets >= 2 && !suspended.includes(definition.id); const weight = Math.max(.8, Math.min(1.2, Number(confirmedWeights[definition.id] ?? 1))); const weightBonus = (weight - 1) * 25; const score = rows.length ? averageReturnPct * 12 + passMarkets * 18 - worstDrawdownPct * 2 + Math.min(rows.reduce((sum, item) => sum + item.trades, 0), 120) * .08 + (reviewed ? (100 - invalidRatePct) * .12 : 0) + weightBonus : Number.NEGATIVE_INFINITY; return { model: definition.id, score, averageReturnPct, worstDrawdownPct, passMarkets, totalMarkets: rows.length, forwardReviewed: reviewed, invalidRatePct, eligible }; }).sort((left, right) => Number(right.eligible) - Number(left.eligible) || right.score - left.score); }
export function loadAdaptiveState() { if (typeof window === 'undefined') return INITIAL_ADAPTIVE_STATE; try { const raw = JSON.parse(window.localStorage.getItem(STORAGE_KEY) ?? '{}') as Partial<AdaptiveState>; return { ...INITIAL_ADAPTIVE_STATE, ...raw, timeframeDecisions: { ...INITIAL_ADAPTIVE_STATE.timeframeDecisions, ...(raw.timeframeDecisions ?? {}) } }; } catch { return INITIAL_ADAPTIVE_STATE; } }
export function saveAdaptiveState(state: AdaptiveState) { if (typeof window !== 'undefined') window.localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }
export function audit(type: AdaptiveAudit['type'], text: string): AdaptiveAudit { return { id: `adaptive-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`, time: new Date().toISOString(), type, text }; }
